# Railway Configuration for Flexboard Control Plane API
# This file is automatically recognized by Railway

[build]
  # Build command - installs dependencies and generates Prisma client
  command = "pnpm install && pnpm run build"

[deploy]
  # Start command for production
  startCommand = "pnpm run start"
  
  # Health check configuration
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  
  # Railway will automatically set PORT, but we can override if needed
  # PORT = 3000

[env]
  # Environment variables that Railway should provide
  # DATABASE_URL will be automatically provided by Railway Postgres
  NODE_ENV = "production"
  API_VERSION = "v1"
  API_KEY_PREFIX = "fxb"
  MAX_SYNC_LOG_RETENTION_DAYS = "30"
  
  # These MUST be set in Railway Dashboard for security:
  # JWT_SECRET = "your-super-secret-jwt-key-256-bit"
  # CORS_ORIGINS = "https://your-frontend-domain.com,https://app.yourcompany.com"
